Lab2/Models/Clients.cs
namespace Laboratoire2.Models
{
    public class Clients
    {
        
        public int ID { get; set; }
        public string Nom { get; set; }
        public Commande Commande { get; set; }
    }
}

Lab2/Models/Commande.cs
namespace Laboratoire2.Models
{
    public class Commande
    {
        public int ID { get; set; }
        public DateTime DateCommande { get; set; }
        public Vetement Vetement { get; set; }
        public void ConfirmerCommande() { 
        }
    }
}

Lab2/Models/ErrorViewModel.cs
namespace Laboratoire2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Lab2/Models/Inventaire.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

namespace Laboratoire2.Models
{
    public class Inventaire
    {
        public int ID { get; set; }
        public List<Vetement> Vetement { get; set; }

    }
}

Lab2/Models/LigneCommande.cs
namespace Laboratoire2.Models
{
    public class LigneCommande
    {
        public int Id { get; set; }
        public Commande Commande { get; set; }
        public int Quantite { get; set; }
        public int Restant { get; set; }
    }

}

Lab2/Models/LigneInventaire.cs
namespace Laboratoire2.Models
{
    public class LigneInventaire
    {
        public int Id { get; set; }
        public Vetement Vetement { get; set; }
        public LigneCommande LigneCommande { get; set; }
        public Inventaire Inventaire{ get; set; }
    }
}

Lab2/Models/Paniers.cs
using System.Collections.Generic;

namespace Laboratoire2.Models
{
    public class Paniers
    {
        public int ID { get; set; }
        public List<Commande> Commande { get; set; }
    }
}

Lab2/Models/Vetement.cs
namespace Laboratoire2.Models
{
    public class Vetement
    {
        public int ID{ get; set; }
        public string NomVetement { get; set; }
        public int QtyVetement { get; set; }
        public int ResteVetement { get; set; }
    }
}

Lab2/Controllers/AdministrateurController.cs
using Microsoft.AspNetCore.Mvc;
using Laboratoire2.Models;
namespace Laboratoire2.Controllers
{
    public class AdministrateurController:Controller
    {
        public List<Clients> clients = new();
        private ContexteApplication Contexte = new();
        public IActionResult Index()
        {
            return Json( DateTime.Now.ToString()+" Creation utilisateur");
        }
        public IActionResult CreerUtilisateur(String Nom)
        {
            Clients cl = new();
            if (cl.ID ==clients.Count)
            {
                return BadRequest();
            }
            else
            {
                cl.ID = clients.Count+1;
                cl.Nom = Nom;
                clients.Add(cl);
                Contexte.SaveChanges();

                return Json($"\n{DateTime.Now} utilisateur créé");
            }
        }
        public IActionResult ModifierUtilisateur(int ID, String Nom)
        {
            Clients cl = new()
            {
                ID = ID,
                Nom = Nom
            };
            clients.Add(cl);
            Contexte.SaveChanges();
            return Json($"\n{DateTime.Now} utilisateur modifié");
        }
        public IActionResult SupprimerUtilisateur(int ID)
        {
            Clients cl = new();
            if (cl.ID == ID)
            {
                return BadRequest();
            }
            else
            {
                cl.ID = ID;
                clients.Remove(cl);
                Contexte.SaveChanges();
                return Json($"\n{DateTime.Now} utilisateur supprime");
            }
        }
    }
}

Lab2/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Laboratoire2.Models;
using System.Diagnostics;

namespace Laboratoire2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private ContexteApplication _contexteApplication;

        public HomeController(ILogger<HomeController> logger, ContexteApplication contexte)
        {
            _logger = logger;
            _contexteApplication = contexte;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return this.View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Lab2/Controllers/PaniersController.cs
using Laboratoire2.Models;
using Microsoft.AspNetCore.Mvc;

namespace Laboratoire2.Controllers
{
    public class PaniersController:Controller
    {
        public int IdPanier { get; set; }
        public string NomVetement { get; set; }
        public int QtyCommande { get; set; }
        public Inventaire Inventaire { get; set; }
        public Clients clients { get; set; }
        public IActionResult Index()
        {
            return View();
        }

    }
}

Lab2/Controllers/VetementsController.cs
using Microsoft.EntityFrameworkCore;
using Laboratoire2.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace Laboratoire2.Controllers
{
    public class VetementsController:Controller
    {
        List<Vetement> vetement = new();
        private ContexteApplication contexte = new();
         public IActionResult Index()
        {
            return View();
        }
        public IActionResult CreerVetement(int IdVetement, string Description, int quantite)
        {
            Vetement vet = new();
            if (IdVetement != 0 && Description != null && quantite != 0)
            {
                vet.ID = IdVetement;
                vet.NomVetement = Description;
                vet.QtyVetement = vet.ResteVetement + quantite;
                vetement.Add(vet);
                contexte.SaveChanges();
                return Json($"\n{Description} Créé.");
            }
            else 
            {
                return BadRequest();

            }
        }
        public IActionResult ModifierItem(int IdVetement, string Description, int quantite)
        {
            return BadRequest();
        }
    }
}

Lab2/Views/Administrateur/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div>
    
    <table>
        <tr> Xavier et Patrice présentent laboratoire 2</tr>
        <td>
            <form asp-controller="Administrateur" asp-action="Creerutilisateur">
                <p>votre nom:</p>
                <input type="text" name="Nom" value="" />
                <input type="submit" name="inscrire" value="valider" />
            </form>
        </td>
    </table>
<table>
    <td>
        <form asp-action="Client">
            <input type="submit" name="action" value="Consulter son panier" />
        </form>
    </td>
</div>
    </table>

Lab2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div>
    
    <table>
        <tr> Xavier et Patrice présentent laboratoire 2</tr>
        <td>
            <form asp-controller="Administrateur" asp-action="index">
                <input type="submit" name="inscrire" value="S'inscrire" />
            </form>
        </td>
    <td>
        <form asp-action="Client">
            <input type="submit" name="action" value="Consulter son panier" />
        </form>
    </td>
    </table>
</div>

Lab2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Laboratoire2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Laboratoire2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Laboratoire2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Bienvenue chez l'équipe 4'</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">À propos de nous</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Laboratoire2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>